import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/Nav";
import SIdeBar from "./(components)/SIdeBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJs-Prototype",
  description: "Generated by Ploydyy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <Nav />
          <div className="flex h-screen overflow-hidden bg-page">
            <SIdeBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
